services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "9001:9001" 
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf # Configuration file
      - ./config/mosquitto/data:/mosquitto/data # Persistent data
      - ./config/mosquitto/log:/mosquitto/log # Log files

volumes:
  db_data:
